### ISSUE TITLE
Windowss

### ISSUE THREAD

**Issue by ci70** [njlr/buck-single-header#1]
Doesn't seem to work on windows.

```
C:\Users\Administrator\Desktop\Buck>buck build :mathutils
Not using buckd because watchman isn't installed.
Parsing buck files: finished in 1.9 sec
Buck wasn't able to parse C:\Users\Administrator\Desktop\Buck\BUCK:
IOError: [Errno 2] No such file or directory: 'C:\\Users\\Administrator\\Desktop\\Buck/C:\\Users\\Administrator\\Desktop\\Buck\\BUCK'
Call stack:
```

**Comment by njlr** [comment]
I added an entry for `cmd_exe` to the genrule: https://github.com/njlr/buck-single-header/blob/c75ff9d09668fc20a7b6f7afdd13efd68db60355/BUCK#L41

Buck allows us to have different commands for Bash platforms and Windows, since they will rarely be exactly the same (https://buckbuild.com/rule/genrule.html#cmd). 

Perhaps it will work now?

**Comment by ci70** [comment]
Can you make an example with a real world library such as JUCE or PCRE2 etc?
